services:
    exporter:
        image: "prom/node-exporter"
        user: "1000:1000"
        command: "--collector.disable-defaults --collector.textfile --collector.textfile.directory=/textfiles"
        volumes:
            - "${FACTORIO_DATA}/script-output/statorio:/textfiles"
        ports:
            - "9100"

    prometheus:
        image: "prom/prometheus"
        user: "1000:1000"
        volumes:
            - "./data/prometheus:/prometheus"
            - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
        ports:
            - "9090:9090"

    grafana:
        image: "grafana/grafana"
        user: "1000:1000"
        environment:
            - "GF_AUTH_ANONYMOUS_ENABLED=true"
            - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
        volumes:
            - "./data/grafana:/var/lib/grafana"
            - "./config/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml"
            - "./config/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml"
            - "./config/grafana/dashboards/:/var/lib/grafana/dashboards/"
        ports:
            - "3000:3000"
