{
 "title": "Factorio",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Active Players",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "factorio_players_connected", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Deaths :(",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(name) (factorio_player_deaths{name!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pave the Planet!",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(surface) (factorio_area_paved{surface!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "The big smoke",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(surface) (factorio_pollution)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}